create table asset_owners
(
    id         bigint primary key generated by default as identity,
    entity_id  bigint references entities (id) not null,
    asset_id   bigint references assets (id)   not null,
    amount     bigint                          not null,
    updated_at timestamp with time zone        not null default now(),
    created_at timestamp with time zone        not null default now()
);

create index on asset_owners (entity_id);
create index on asset_owners (asset_id);
create unique index asset_owners_unique_entity_asset on asset_owners (entity_id, asset_id);

create trigger trigger_asset_owners_updated_at
    before update
    on asset_owners
    for each row
execute procedure set_updated_at_time();
