create table entities
(
    id         bigint primary key generated by default as identity,
    identity   text not null unique, -- indexed (unique)
    created_at timestamp with time zone default now()
);
