create table transactions
(
    id                    bigint primary key generated by default as identity,
    hash                  text unique                     not null, -- indexed (unique)
    source_entity_id      bigint references entities (id) not null,
    destination_entity_id bigint references entities (id) not null,
    amount                bigint                          not null,
    tick                  bigint                          not null,
    input_type            int                             not null,
    input_size            int                             not null,
    extra_data            jsonb                           not null,
    money_flew            boolean,
    created_at            timestamp with time zone default now()
);

CREATE INDEX ON transactions (source_entity_id);
CREATE INDEX ON transactions (input_type);
