create table trades
(
    id               bigint primary key generated by default as identity,
    tick_time        timestamp with time zone               not null,
    transaction_id   bigint references transactions (id)    not null,
    bid              boolean                                not null,
    price            bigint                                 not null,
    number_of_shares bigint                                 not null,
    maker_id         bigint references entities (id), -- not sure if always known
    asset_id         bigint references assets (id)          not null,
    created_at       timestamp with time zone default now() not null
);

CREATE INDEX ON trades (tick_time);
CREATE INDEX ON trades (transaction_id);
CREATE INDEX ON trades (maker_id);
CREATE INDEX ON trades (asset_id);
